defaults:
  - default

strategy:
  _target_: lightning.pytorch.strategies.DDPStrategy
  find_unused_parameters: false

accelerator: gpu
devices: 2  # Updated to match available hardware
# Set to your actual node count
num_nodes: 1  # Using a single node
sync_batchnorm: True
