_target_: lightning.pytorch.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1
max_epochs: 10

accelerator: auto
devices: auto
strategy: ddp

# mixed precision for faster training
precision: ${precision}

# set True to debug the training process checking for NaN or errors
detect_anomaly: false

# control the frequency of various logging outputs
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
val_check_interval: 1.0

# control how many batches to process before logging metrics
log_every_n_steps: 50

# Gradient clipping
gradient_clip_val: 1.0

# Number of nodes for multi-GPU training
num_nodes: 1
