_target_: mattermake.models.hierarchical_crystal_transformer_module.HierarchicalCrystalTransformerModule

# Model architecture parameters
vocab_size: 2000  # Will be overridden by actual tokenizer vocabulary size
hidden_size: 768
num_hidden_layers: 12
num_attention_heads: 12
intermediate_size: 3072
hidden_dropout_prob: 0.1
attention_probs_dropout_prob: 0.1
max_position_embeddings: 1024  # Increased from 512 to handle longer sequences
type_vocab_size: 7

# Hierarchical structure parameters
composition_layers: 3
space_group_layers: 2
lattice_layers: 3
atom_layers: 6
integration_layers: 2

# Learning rate settings
learning_rate: 1e-4
weight_decay: 0.01
warmup_steps: 1000
adam_epsilon: 1e-8

# Curriculum learning settings
use_curriculum: true
composition_curriculum_epochs: 5
space_group_curriculum_epochs: 5
lattice_curriculum_epochs: 5