_target_: src.models.crystal_autoencoder_module.CrystalAutoencoderModule

# Model architecture
input_dim: 95
hidden_dim: 256
latent_dim: 128
encoder_layers: 3
num_heads: 8
timesteps: 1000
beta_start: 0.0001
beta_end: 0.02
beta_schedule: "linear"
num_atom_types: 95
discretize_t: 50
max_atoms: 80
device: "cuda"

# Optimizer settings
learning_rate: 0.0001
weight_decay: 0.000001

# Loss weights
positions_loss_weight: 1.0
lattice_loss_weight: 1.0
atom_types_loss_weight: 1.0

# Learning rate scheduler
scheduler_step_size: 100
scheduler_gamma: 0.5
