_target_: mattermake.models.modular_hierarchical_crystal_transformer_module.ModularHierarchicalCrystalTransformer
element_vocab_size: 100
sg_vocab_size: 231
wyckoff_vocab_size: null  # Auto-calculated from wyckoff interface
pad_idx: 0
start_idx: -1
end_idx: -2
d_model: 512
type_embed_dim: 128
wyckoff_embed_dim: 128
nhead: 8
num_atom_decoder_layers: 6
dim_feedforward: 2048
dropout: 0.1
encoder_configs:
  composition:
    num_layers: 3
  spacegroup:
    embed_dim: 128
  lattice:
    latent_dim: 128
    equivariant: false
    has_conditioning: true
    depends_on:
    - composition
    - spacegroup
  wyckoff:
    embed_dim: ${model.wyckoff_embed_dim}
    has_conditioning: true
    depends_on:
    - spacegroup
  atom_type:
    element_vocab_size: ${model.element_vocab_size}
    type_embed_dim: ${model.type_embed_dim}
    num_layers: 3
    nhead: ${model.nhead}
    dim_feedforward: ${model.dim_feedforward}
    dropout: ${model.dropout}
    pad_idx: ${model.pad_idx}
    start_idx: ${model.start_idx}
    end_idx: ${model.end_idx}
    has_conditioning: true
    depends_on:
    - composition
    - spacegroup
    - lattice
    - wyckoff
  coordinate:
    hidden_dim: 256
    num_layers: 3
    nhead: ${model.nhead}
    dim_feedforward: ${model.dim_feedforward}
    dropout: ${model.dropout}
    has_conditioning: true
    depends_on:
    - composition
    - spacegroup
    - lattice
    - wyckoff
learning_rate: 5e-5
weight_decay: 0.01
# Learning rate scheduling
lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 100
  eta_min: 1e-6
warmup_steps: 1000
use_lr_scheduler: true
sg_loss_weight: 1.0
lattice_loss_weight: 1.0
wyckoff_loss_weight: 1.0
type_loss_weight: 1.0
coord_loss_weight: 1.0
eps: 1e-6
decoder_configs:
  spacegroup:
    sg_vocab_size: 230
  lattice: null
  wyckoff:
    condition_on:
    - sg
  atom_type: null
  coordinate:
    eps: 1e-6
encoding_order:
- composition
- spacegroup
- lattice
- wyckoff
- atom_type
- coordinate
decoding_order:
- spacegroup
- lattice
- wyckoff
- atom_type
- coordinate
