# @package _global_

defaults:
  - _self_
  - paths: default
  - hydra: default

task_name: "data_preparation"

# Input data file (pickle with embeddings and slices)
input_path: "/p/project1/hai_solaihack/datasets/slices/embeddings_with_slices"

# Output directory for processed data
output_dir: "${paths.data_dir}/slice"

# Ratio of data to use for training (rest for validation)
train_ratio: 0.9

# Factor to limit the amount of data used (1.0 means use all data)
data_limit_factor: 1.0

# Random seed for reproducibility
seed: 42
