# @package _global_

defaults:
  - _self_
  - model: crystal_diffusion.yaml
  - paths: default.yaml
  - hydra: default.yaml

# Task name for Hydra configuration
task_name: "generate_crystals"

# Path to the checkpoint of the trained model
ckpt_path: ${paths.log_dir}/train_diffusion/runs/last/checkpoints/last.ckpt

# Device to run the model on
device: "cuda"

# Generation parameters
num_samples: 100
generation_batch_size: 16
num_atoms: 30  # Set to 0 to use default from model config

# Path to conditioning data (optional, set to null to skip)
condition_path: null

# Output path to save results
output_path: ${paths.root_dir}/results/generated_crystals.json

# For reproducibility
seed: 42
