# @package _global_

defaults:
  - _self_
  - model: gpt.yaml
  - paths: default.yaml
  - hydra: default.yaml

# Add task name for Hydra configuration
task_name: "generate_slice"

# Path to the checkpoint of the trained model
ckpt_path: ${paths.log_dir}/train/runs/2025-03-06_14-03-51/checkpoints/last.ckpt

# Device to run the model on
device: "cuda"

# Data to generate from
data_path: ${paths.data_dir}/slice/val.pt

# Generation parameters
num_samples: 10 #198581
max_new_tokens: 100
temperature: 0.3
top_k: 30
show_original: true

# Performance optimization
generation_batch_size: 128
evaluate_all: false

# Output path to save results (set to null to skip saving)
output_path: ${paths.root_dir}/results/generation_results_cross_110M_full.json

# For reproducibility
seed: 42
