# @package _global_

defaults:
  - _self_
  - paths: default.yaml
  - hydra: default.yaml

task_name: "prepare_crystal_data"

# Input data configuration
input_csv: "/p/project1/hai_solaihack/datasets/mp_20/train.csv"  # Adjust path as needed
output_dir: "${paths.data_dir}/crystal_data"

# Data processing parameters
max_seq_length: 512
coord_precision: 4
split_ratio: 0.1  # Validation split ratio
standardize: true  # Whether to standardize structures
symprec: 0.01  # Symmetry precision

# Column names in CSV
material_id_col: "material_id"
cif_col: "cif"

# For testing/debugging - set to null to process all structures
max_structures: null