# @package _global_

defaults:
  - _self_
  - model: crystal_autoencoder.yaml
  - data: crystal_datamodule.yaml
  - paths: default.yaml
  - hydra: default.yaml

# Task name for Hydra configuration
task_name: "validate_autoencoder"

# Path to the checkpoint of the trained model
ckpt_path: ${paths.log_dir}/train_autoencoder/runs/last/checkpoints/last.ckpt

# Device to run the model on
device: "cuda"

# Path to validation data (if not using data module)
val_data_path: ${paths.data_dir}/processed/val.pt

# Number of samples to validate
num_samples: 100

# Output path to save results
output_path: ${paths.root_dir}/results/autoencoder_validation.json

# For reproducibility
seed: 42
